language: python
python:
  - "2.7"
install:
  - cd ryu; python ./setup.py install; cd ..
  - pip install greenlet
  - pip install repoze.lru
  - pip install coverage
  - pip install coveralls
  - pip install mock
script:
  - nosetests --with-coverage --cover-package=greenmst
after_success:
  - coveralls

